name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
        distribution: 'temurin'
        cache: maven
        
    - name: Heroku Action    
      uses: CDNievas/heroku-action@v1.0    

      with:
        heroku_api_key: ${{secrets.APP_KEY}}
        heroku_email: ${{secrets.APP_EMAIL}}
        heroku_app_name: ${{secrets.APP_NAME}}
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
